### ISSUE TITLE
No sound in inf-20100415 without wi-fi connection

### ISSUE THREAD

**Issue by Gruby5588** [kcxx/RetroWrapper#13]

**Comment by Gruby5588** [comment]
log
mar 23, 2018 6:04:41 PM net.minecraft.launchwrapper.LogWrapper log
INFO: Using tweak class name com.zero.retrowrapper.RetroTweaker
mar 23, 2018 6:04:41 PM net.minecraft.launchwrapper.LogWrapper log
INFO: Launching wrapped minecraft
******************************
*     old mojang servers     *
*       emulator by 000      *
******************************
Old servers emulator is running!
Probably the Minecraft class (it has run && is applet!): net.minecraft.client.d
Client asked for parameter: fullscreen
Found URL!: http://www.minecraft.net/skin/
Replaced with: http://127.0.0.1:27035/skin/
43
Client asked for parameter: mppass
Client asked for parameter: loadmap_user
Client asked for parameter: server
Found likely Minecraft candidate: private net.minecraft.client.d net.minecraft.client.MinecraftApplet.b
Loading current icons for window from: C:\Users\Mateusz\AppData\Roaming\.minecraft\assets\virtual\legacy\icons\icon_16x16.png and C:\Users\Mateusz\AppData\Roaming\.minecraft\assets\virtual\legacy\icons\icon_32x32.png
java.net.UnknownHostException: launchermeta.mojang.com
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.connect(Unknown Source)
	at sun.security.ssl.BaseSSLSocketImpl.connect(Unknown Source)
	at sun.net.NetworkClient.doConnect(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.protocol.https.HttpsClient.<init>(Unknown Source)
	at sun.net.www.protocol.https.HttpsClient.New(Unknown Source)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
	at java.net.URL.openStream(Unknown Source)
	at com.zero.retrowrapper.emulator.registry.handlers.ResourcesHandler.downloadSoundData(ResourcesHandler.java:54)
	at com.zero.retrowrapper.emulator.registry.handlers.ResourcesHandler.<init>(ResourcesHandler.java:49)
	at com.zero.retrowrapper.emulator.registry.EmulatorRegistry.registerAll(EmulatorRegistry.java:41)
	at com.zero.retrowrapper.emulator.RetroEmulator.run(RetroEmulator.java:28)
LWJGL version: 2.9.3
GL RENDERER: GeForce 940M/PCIe/SSE2
GL VENDOR: NVIDIA Corporation
GL VERSION: 4.5.0 NVIDIA 385.41
OpenGL 3.0: true
OpenGL 3.1: true
OpenGL 3.2: true
ARB_compatibility: true
PROFILE MASK: 0
CORE PROFILE: false
COMPATIBILITY PROFILE: false
mar 23, 2018 6:04:47 PM net.java.games.input.DefaultControllerEnvironment getControllers
WARNING: Found unknown Windows version: Windows 10
mar 23, 2018 6:04:47 PM net.java.games.input.DefaultControllerEnvironment getControllers
INFO: Attempting to use default windows plug-in.
mar 23, 2018 6:04:47 PM net.java.games.input.DefaultControllerEnvironment getControllers
INFO: Loading: net.java.games.input.DirectAndRawInputEnvironmentPlugin
Found URL!: Author: Paul Lamb, www.paulscode.com
Replaced with: 127.0.0.1:27035

Starting up SoundSystem...
Initializing LWJGL OpenAL
    (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
AL lib: (EE) MMDevApiOpenPlayback: Device init failed: 0x80004005
AL lib: (EE) MMDevApiOpenPlayback: Device init failed: 0x80004005
Error in class 'LibraryLWJGLOpenAL'
    Unable to initialize OpenAL.  Probable cause: OpenAL not supported.
    ERROR MESSAGE:
        Could not locate OpenAL library.
    STACK TRACE:
        org.lwjgl.openal.AL.create(AL.java:156)
        org.lwjgl.openal.AL.create(AL.java:102)
        org.lwjgl.openal.AL.create(AL.java:206)
        paulscode.sound.libraries.LibraryLWJGLOpenAL.init(Unknown Source)
        paulscode.sound.SoundSystem.CommandNewLibrary(Unknown Source)
        paulscode.sound.SoundSystem.CommandQueue(Unknown Source)
        paulscode.sound.CommandThread.run(Unknown Source)
    ERROR MESSAGE:
        Could not locate OpenAL library.

Starting up SoundSystem...
Switching to No Sound
    (Silent Mode)

java.net.UnknownHostException: teamvj.esy.es
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at sun.net.NetworkClient.doConnect(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.http.HttpClient.<init>(Unknown Source)
	at sun.net.www.http.HttpClient.New(Unknown Source)
	at sun.net.www.http.HttpClient.New(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.net.URL.openStream(Unknown Source)
	at net.minecraft.client.i.run(Unknown Source)
